language: php
php:
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --no-interaction
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - bin/coveralls -v