services:
    # Event Listener for kernel response
    temirkhan_on_response_flush_listener.response_flush_listener:
        class: Temirkhan\OnResponseFlushListenerBundle\EventListener\OnResponseFlushListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    # Event Listener for flushing prevention
    temirkhan_on_response_flush_listener.response_flush_prevent_listener:
        class: Temirkhan\OnResponseFlushListenerBundle\EventListener\OnResponseFlushListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: transaction.rollback, method: onTransactionRollback}